config/routes.rb
require 'sidekiq/web'
Pwf::Application.routes.draw do

  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_scope :user do
    get "login", to:  "sessions#new"
    get "logout", to: "sessions#destroy"
    get "users", to: "sessions#new"
  end

  root to: "home#index"


  get 'dashboard', :to => 'dashboards#show'
  get 'registration_closed' => "home#closed", :as => :registration_closed
  get 'registration_confirmation/:registration_id', to: 'student_registration_confirmations#show', as: :registration_confirmation
  get 'edit_my_waitlist', to: 'parent_waitlist#edit', as: :edit_my_waitlist
  patch 'update_my_waitlist', to: 'parent_waitlist#update', as: :update_my_waitlist
  get 'waitlist_upated', to: 'parent_waitlist#thanks', as: :waitlist_updated

  resources :groups
  resources :aep_registrations
  resources :aep_sessions
  resources :attendances
  resources :attendance_sheets do
   resources :attendances
  end

  resources :contact_details

  resources :grades
  resources :monthly_reports
  resources :parents do
    resources :demographics
  end
  resources :payments, only: [:new, :index,:show, :create] do
    collection do
      get :paypal_success
      get :paypal_cancel
      post :notify
    end
  end

  resources :report_cards do
    get :transcript, :on => :member
  end

  resources :seasons

  resources :student_registrations do
    get :withdraw, on: :member
  end

  resources :student_assessments
  resources :students do
    get :avatar, :on => :member
  end

  resources :image_uploads, :only => [:create]

end

app/models/student_registration.rb
class StudentRegistration < ApplicationRecord

  SIZES = %w(Kids\ xs Kids\ S Kids\ M Kids\ L S M L XL 2XL 3XL)
  as_enum :size, SIZES.each_with_index.inject({}) {|h, (item,idx)| h[item]=idx; h}

  STATUS_VALUES = ["Pending", "Confirmed Fee Waived", "Confirmed Paid", "Wait List", "Withdrawn", "AEP Only", "Blocked On Report Card"]
  as_enum :status, STATUS_VALUES.map{|v| v.parameterize.underscore.to_sym}, pluralize_scopes:false 

  belongs_to :season
  belongs_to :student, inverse_of: :current_registration
  belongs_to :payment, optional: true
  belongs_to :group, optional: true

  has_many :attendances, dependent: :destroy
  has_many :report_cards, dependent: :destroy
  has_one :aep_registration, dependent: :destroy
  has_one :fall_winter_report_card,  ->{where("marking_period_id = ?", MarkingPeriod.first_session_id)}, class_name: "ReportCard"
  has_one :spring_summer_report_card,  ->{where("marking_period_id = ?", MarkingPeriod.second_session_id)}, class_name: "ReportCard"
  has_one :parent, :through => :student

  before_save :determine_status

  validates :season, :school, :grade, :size_cd,  :presence => :true
  validates_uniqueness_of :student, scope: :season, message: "This student is already registered"
  validates :student, :presence => true, :on => :save

  delegate :name, :first_name, :last_name, :dob, :gender, :ethnicity,  :to => :student,:prefix => true
  delegate :id, :name, :email, :first_name,  :to => :parent,:prefix => true
  delegate :term, to: :season

  scope :report_card_exempt, ->{where(report_card_exempt: true)}
  scope :report_card_required, ->{where("grade <= 12").where.not(id: report_card_exempt)}
  scope :with_aep, ->{joins(:aep_registration)}
  scope :with_aep_paid, ->{with_aep.merge(AepRegistration.confirmed)}
  scope :with_aep_unpaid, ->{with_aep.current.confirmed.merge(AepRegistration.unpaid)}
  scope :in_aep, ->{with_aep_paid.confirmed}
  scope :not_in_aep, -> { where.not(id: in_aep)}
  scope :in_training_program, -> { where(in_training_program: true)}
  scope :exclude_selected, ->(exclude_list) { where.not(id: exclude_list)}
  scope :hs_seniors, ->{confirmed.where("student_registrations.grade = 12")}

  class << self

    def sizes_table
      sizes.hash.invert
    end

    def missing_report_card_for period
      report_card_required.where.not(id: student_registration_ids_from_current_year_report_card_for_period(period))
    end

    def student_registration_ids_from_current_year_report_card_for_period period
      ReportCard.by_year_and_marking_period(Season.current.academic_year, period)
        .select("student_registration_id")
    end

    def current
      by_season(Season.current_season_id)
    end

    def previous_season
      by_season(Season.previous_season_id)
    end

    def last_confirmed
      confirmed.order("season_id desc").limit(1).first
    end

    def last_enrollment
      where("season_id < ?", Season.current_season_id).order("season_id desc").limit(1)
    end

    def by_season id
      where(season_id: id)
    end

    def current_confirmed_report_required
      StudentRegistration.includes(:student).current.confirmed.report_card_required
    end

    def current_confirmed
      current.confirmed
    end

    def current_pending
      current.pending
    end

    def current_wait_listed
      current.wait_listed
    end

    def current_withdrawn
      current.withdrawn
    end

    def confirmed_students_count
      current_confirmed.count
    end

    def current_count
      current.count
    end

    def current_blocked_on_report_card
      current.blocked_on_report_card
    end

    def inactive
      where.not(id: current)
    end

    def status_options
      statuses.hash
    end

    def size_options
      sizes.hash
    end

    def unpaid
      pending
    end

    def paid
      confirmed_paid
    end

    def fee_waived
      confirmed_fee_waived
    end

    def confirmed
      confirmed_paid.or(confirmed_fee_waived)
    end

    def wait_listed
      wait_list
    end

    def current_wait_listed_count
      current_wait_listed.count
    end

    def wait_listed_count
      wait_listed.count
    end

    def with_valid_report_card
      where(report_card_submitted: true)
    end

    def ineligible
      where(report_card_submitted: false)
    end

    def order_by_student_last_name
      select(:first_name, :last_name, :student_id, :size_cd).joins(:student).order("students.last_name asc, students.first_name asc")
    end

    def in_aep_count
      in_aep.count
    end

    def set_statuses regs, status
      regs.each{|r| r.status = status}
    end

    def set_pending_to_waitlist
      current_pending.each{|r|r.wait_list!}
    end

  end

#----------- End Eigen Class ------------------#

  def renew
    return if season.current? or student.student_registrations.current.exists?
    new_registration  = self.dup
    new_registration.season = Season.current
    new_registration.grade = grade+1
    new_registration.pending!
    new_registration.payment = nil
    new_registration.report_cards = []
    new_registration.report_card_submitted = false
    new_registration.first_report_card_received = false
    new_registration.first_report_card_received_date = nil
    new_registration.second_report_card_received = false
    new_registration.second_report_card_received_date = nil
    new_registration.save
  end

  def ytd_attendance
    AttendanceSheet.current.map do |sheet|
      {id: sheet.id, date: sheet.session_date}.merge(sheet.status_for(id))
    end
  end

  def paid?
    !payment_id.nil?
  end

  def enrolled_in_aep?
    aep_registration.present? 
  end

  def season_description
    season.description
  end

  def parent_name
    parent.name
  end

  def unconfirmed?
    not confirmed?
  end

  def confirmed?
    [:confirmed_paid, :confirmed_fee_waived].include? status
  end

  def mark_as_paid(payment)
    self.payment = payment
    self.status = :confirmed_paid 
    save
  end

  def description
    "Fencing #{student_name} - #{season.slug}"
  end

  def attendance_count
    attendances.any? ? attendances.count : 0;
  end

  def fee
    season.fencing_fee
  end

  def is_missing_first_report_card?
    !current_report_cards.first_session_transcript_provided?
  end

  def is_missing_second_report_card?
    !current_report_cards.second_session_transcript_provided?
  end

  def requires_last_years_report_card?
    return false if report_card_exempt?
    tracker = StudentReportCardTracker.new(student, Season.previous.academic_year)
    student.enrolled_last_season? && tracker.has_not_uploaded_first_and_second_report_card_for_season?
  end

  def current_report_cards
    @curr_report_cards ||= StudentReportCardTracker.new(student, Season.current.academic_year)
  end

  def age
    season_start = season.beg_date
    season_start.year - student_dob.year - ((season_start.month > student_dob.month || (season_start.month == student_dob.month && season_start.day >= student_dob.day)) ? 0 : 1)
  end

  private

  def determine_status
    new_status = status

    self.status = case 
                  when season.wait_list?
                    :wait_list
                  when requires_last_years_report_card?
                    :blocked_on_report_card
                  else
                    new_status
                  end
  end
end

app/controllers/student_registrations_controller.rb
class StudentRegistrationsController < ApplicationController
  before_action :get_registration, only:[:show, :edit, :destroy, :update, :withdraw]

  def new
    if params[:student_id]

      @student = current_user.students.find(params[:student_id])
      resp = StudentRegistrationAuthorizer.can_register? @student
      if resp.answer == false
        redirect_to @student, alert: resp.message
      end
      @student_registration = @student.student_registrations.build
    else
      redirect_to dashboard_path, :alert => "No student found to create registration"
    end
  end

  def edit

  end

  def withdraw

  end

  def create
    @student_registration = StudentRegistration.new(student_registration_params)

    if @student_registration.save
      StudentRegistrationMailer.notify(@student_registration).deliver_later
      WaitListService.activate_if_enrollment_limit_reached
      redirect_to dashboard_path, notice: "Student registration successfully created"
    else
      render :new
    end
  end

  def destroy
    @student_registration.destroy
    redirect_to dashboard_path
  end

  def update
    if  @student_registration.update_attributes(student_registration_params)
      if request.xhr?
        head :ok;
      else
        redirect_to dashboard_path and return
      end
    else
      render :edit
    end
  end

  private

  def get_registration
    @student_registration = current_user.student_registrations.find(params[:id])
      rescue ActiveRecord::RecordNotFound
    redirect_to dashboard_path if @student_registration.nil?
  end

  def student_registration_params
    params.require(:student_registration).permit(
  :school, :grade, :size_cd, :medical_notes, 
    :academic_notes, :academic_assistance, :student_id, :season_id, 
    :status_cd)
  end

end

app/views/student_registrations/_form.html.erb
<div class="row">
  <%= render partial: "students/student_info_widget", locals: {student: @student_registration.student} %>
  <div class="col-md-6 col-sm-12">
    <div class="card card-info">
      <%= simple_form_for(@student_registration, :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="card-header">
          <h3 class="card-title"><%=Season.current.description%></h3>
        </div>
        <div class="card-body">
          <%= f.hidden_field :student_id, value: @student_registration.student.id%>
          <%= f.input :school, :input_html => {:id => "school"}%>
          <%= f.hidden_field :season_id, value: Season.current.id %>
          <%= f.input :grade,  :input_html => {:id => "grade", :min  => 4, :max=> 12}%>
          <%= f.input :size_cd, :collection =>StudentRegistration.size_options , :input_html => {:id => "size"}, :label => "Size" %>
          <%= f.input :medical_notes,  :input_html => {:id => "medical_notes",:rows => 5}%>
          <%= f.input :academic_notes, :input_html => {:id => "academic_notes", :rows => 5 }%>
          <%= f.input :academic_assistance, label: "I'm interested in Academic Enrichment Program", :input_html => {:id => "academic_assistance"}%>
        </div>
        <div class="card-footer">
          <%= f.button :submit, "Submit", :id =>"submit", class: "btn btn-info " %>
          <%= link_to 'Cancel', dashboard_path,  class: "btn btn-default float-right"%>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/student_registrations/edit.html.erb
<%= render 'form' %>

app/views/student_registrations/index.html.erb
<h1>Students</h1>

<table class="dtable table table-striped">
  <tr>
    <th>Season</th>
    <th>School</th>
    <th>Grade</th>
    <th>Size</th>
    <th>Medical notes</th>
    <th>Academic notes</th>
    <th>Academic assistance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_registrations.each do |student_registration| %>
  <tr>
    <td><%= student_registration.season %></td>
    <td><%= student_registration.school %></td>
    <td><%= student_registration.grade %></td>
    <td><%= student_registration.size %></td>
    <td><%= student_registration.medical_notes %></td>
    <td><%= student_registration.academic_notes %></td>
    <td><%= student_registration.academic_assistance %></td>
    <td><%= link_to 'Show', student_registration %></td>
    <td><%= link_to 'Edit', edit_student_registration_path(student_registration) %></td>
    <td><%= link_to 'Destroy', student_registration, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student registration', new_student_registration_path %>

app/views/student_registrations/new.html.erb
<%content_for :page_hdr do%>
 New Registration
<%end%>
<%= render 'form' %>

app/views/student_registrations/withdraw.html.erb
<%content_for :page_hdr do%>
  Student Withdrawal Request
<%end%>

<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="callout callout-danger">
      <blockquote>
        <p>
        <small>By clicking "Withdraw Student" you will cancel your student's enrollment for the current season. If the student is also enrolled in the Academic Enrichment Program that enrollment will also be canceled.  Withdrawn students are not allowed to attend either the fencing program nor the AEP. Enrollment fees for the fencing program are not refundable.
        </small>
        </p>
      </blockquote>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="card card-danger">
      <%= simple_form_for(@student_registration, :html => { :class => 'form-horizontal', method: :patch, data:{confirm: "Are you sure"} }) do |f| %>
        <div class="card-body">
          <%= f.hidden_field :student_id, value: @student_registration.student.id%>
          <%= f.hidden_field :status_cd, value: StudentRegistration.statuses[:withdrawn] %>
          <%= f.input :academic_notes, label: "Withdrawal Reason (optional)", :input_html => { :rows => 5 }%>
        </div>
        <div class="card-footer">
          <%= f.button :submit, "Submit", :id =>"submit", class: "btn btn-danger " %>
          <%= link_to 'Cancel', dashboard_path,  class: "btn btn-default float-right"%>
        </div>
      <% end %>
    </div>
  </div>

  <%= render partial: "students/student_info_widget", locals: {student: @student_registration.student} %>
</div>