config/routes.rb
require 'sidekiq/web'
Pwf::Application.routes.draw do

  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_scope :user do
    get "login", to:  "sessions#new"
    get "logout", to: "sessions#destroy"
    get "users", to: "sessions#new"
  end

  root to: "home#index"


  get 'dashboard', :to => 'dashboards#show'
  get 'registration_closed' => "home#closed", :as => :registration_closed
  get 'registration_confirmation/:registration_id', to: 'student_registration_confirmations#show', as: :registration_confirmation
  get 'edit_my_waitlist', to: 'parent_waitlist#edit', as: :edit_my_waitlist
  patch 'update_my_waitlist', to: 'parent_waitlist#update', as: :update_my_waitlist
  get 'waitlist_upated', to: 'parent_waitlist#thanks', as: :waitlist_updated

  resources :groups
  resources :aep_registrations
  resources :aep_sessions
  resources :attendances
  resources :attendance_sheets do
   resources :attendances
  end

  resources :contact_details

  resources :grades
  resources :monthly_reports
  resources :parents do
    resources :demographics
  end
  resources :payments, only: [:new, :index,:show, :create] do
    collection do
      get :paypal_success
      get :paypal_cancel
      post :notify
    end
  end

  resources :report_cards do
    get :transcript, :on => :member
  end

  resources :seasons

  resources :student_registrations do
    get :withdraw, on: :member
  end

  resources :student_assessments
  resources :students do
    get :avatar, :on => :member
  end

  resources :image_uploads, :only => [:create]

end

app/models/report_card.rb
class ReportCard < ApplicationRecord

  attr_accessor :transcript_pages

  has_one_attached :transcript
  belongs_to :student_registration
  belongs_to :marking_period
  has_one :student, through: :student_registration
  has_one :season, through: :student_registration
  has_many :grades
  accepts_nested_attributes_for :grades, allow_destroy: true

  validates_uniqueness_of :marking_period_id, scope: [:student_registration_id, :academic_year], message: "Student already has a report card for this marking period and academic year"
  validates :student_registration, :academic_year, :marking_period, presence: true
  validate  :transcript_uploaded

  scope :current, ->{includes(:student_registration).references(:student_registration).where("student_registrations.season_id = ?", Season.current.id)}
  scope :previous, ->{joins(:student_registration).where.not("student_registrations.season_id =?", Season.current)}
  scope :graded, ->{joins(:student_registration).includes(:grades).references(:grades).where.not(grades: {id: nil})}
  scope :not_graded, ->{joins(:student_registration).includes(:grades).references(:grades).where(grades: {id: nil})}
  scope :with_transcript, ->{joins(:transcript_attachment).where('active_storage_attachments.created_at <= ?', Time.now)}
  scope :by_academic_year,  ->(school_year){where(academic_year: school_year)}
  scope :by_marking_period,  ->(period){where(marking_period: period)}
  scope :by_year_and_marking_period,  ->(school_year, period){by_academic_year(school_year).by_marking_period(period)}
  delegate :slug,  to: :season, prefix: true
  delegate :term, to: :season
  delegate :name, to: :marking_period, prefix: true

  before_validation :attach_pages_if_present, :set_academic_year
  before_create :set_student
  after_create :update_invalid_current_registration

  def self.academic_years 
    Season.all.map(&:term)
  end

  def self.in_wrong_season
    where("transcript is not null and season_id = ? and created_at < ?",Season.current.id,  Season.current.beg_date)
  end

  def marking_period_name
    marking_period.name
  end

  def student_name
    student.nil? ? "invalid" : student.name 
  end

  def student_id
    student.nil? ? "000000" : student.id
  end

  def has_grades?
    grades.any?
  end

  def slug
    "#{marking_period_name}: #{season.slug}"
  end

  def description
    "#{marking_period_name}-#{academic_year}"
  end

  def subject_list
    Subject.all.as_json(only: [:id,:name])
  end


  def reassign_to_last_season
    if student.previous_registration
      self.season_id = Season.previous_season_id 
      self.student_registration_id = student.previous_registration.id
    end
    save
  end

  def transcript_modified?
    @transcript_modified
  end

  def average
    return 0 if grades.empty?
    num = grades.map(&:score).sum/grades.count
    num.round(2)
  end

 private

  def update_invalid_current_registration
    if student.current_registration && student.current_registration.blocked_on_report_card?
      tracker = StudentReportCardTracker.new student, Season.previous.academic_year
      tracker.unblock_current_registration
    end
  end


  def attach_pages_if_present
    if transcript_pages.present? && marking_period.present?
      pdf = FileUploadToPdf.combine_uploaded_files transcript_pages
      transcript.attach(io: pdf, filename: "#{slug}.pdf", content_type: "application/pdf")
      @transcript_modified= true
    end

  rescue FileUploadToPdf::IncompatibleFileTypeForMergeError
    errors.add(:transcript_pages, "All files must be of the same file type")
  end

  def transcript_uploaded
    unless transcript.attached?
      errors.add(:transcript, "file must be attached")
      return false
    end
  end

  def set_student
    self.student_id = student.id
  end

  def set_academic_year
    self.academic_year = season.academic_year if self.academic_year.nil?
  end

end

app/controllers/report_cards_controller.rb
class ReportCardsController < ApplicationController
  before_action :load_student_registrations, only:[:new, :create]
  before_action :load_current, only: [:show, :edit, :update]


  def index
    @report_cards = current_user.report_cards
  end

  def new
    if params[:student_id].present?
      s = Student.find(params[:student_id])
      reg = s.student_registrations.last_confirmed

      if(reg)
        @report_card = reg.report_cards.build
        return
      end
    end

    redirect_to report_cards_path, alert: "You can can only upload report cards
    for students that are currently or have previously attended the PWF"
  end

  def create
    @report_card = ReportCard.new(report_card_params)
    if @report_card.save
      ReportCardMailer.uploaded(@report_card).deliver_later #always deliver since transcript is required on create
      ReportCardMailer.confirmation(@report_card, current_user).deliver_later 
      redirect_to report_cards_path
    else
      flash[:alert]="Unable to create report card"
      render :new
    end
  end

  def update
     @report_card.assign_attributes(report_card_params)
     if  @report_card.valid?
       ReportCardMailer.uploaded(@report_card).deliver_later if @report_card.transcript_modified?
       redirect_to report_cards_path
     else
       flash[:alert]="Unable to update report card"
       render :edit
     end
  end

  #TODO handle redirect after delete more elegantly
  def destroy
    @report_card = ReportCard.find(params[:id])
    @report_card.destroy
    redirect_to report_cards_path
  end

  private


  def add_incompatible_file_type_error
    @report_card.errors.add(:base, "All files must be of the same file type")
    render @report_card.new_record? ? :new : :edit
  end

  def load_current
    @report_card = ReportCard.find(params[:id])
    @student_registrations =[@report_card.student_registration]
  end

  def load_student_registrations
    @student_registrations = current_user.student_registrations.current
  end

  def transcript_modified?
    @report_card.transcript_modified?
  end

  def pages
    @pages ||= params[:report_card][:transcript_pages]
  end

  def notify_transcript_uploaded
    ReportCardMailer.uploaded(@report_card).deliver_later if @report_card.transcript_modified?
  end

  def report_card_params
    params.require(:report_card).permit(:student_registration_id, :season_id, :academic_year, :marking_period_id, :format_cd, {transcript_pages:[]}, :grades_attributes )
  end

end

app/views/report_cards/_form.html.erb
<%= simple_form_for @report_card, :html => { multipart: true, class: 'form-horizontal', id: "report_card_form", :novalidate=>"novalidate"} do |f| %>
  <div class="row">
    <!-- left column -->

    <div class="col-sm-12 col-md-5">
      <div class="card card-secondary">
        <div class="card-header">
          <h3 class="card-title"><%=@report_card.student_name%></h3>
        </div>
        <div class="card-body">
          <%=f.error_notification message: "Please fix the errors listed below", class: "disabled"%>
          <%=f.hidden_field :student_registration_id, value: @report_card.student_registration.id %>
          <%=f.hidden_field :academic_year, value: @report_card.student_registration.term %>
          <%unless @report_card.student.fully_enrolled?%>
          <div class="text-sm callout callout-danger">
            <p class="text-danger">
            <b>Note:</b> <%=@report_card.student_name%> is not yet fully registered for the current season.
            </p>
            <p>
            This report card will be applied to the <%=@report_card.student.student_registrations.last_confirmed.term%> School Year.
            </p>
          </div>
        <%end%>
          <%= f.input :marking_period_id, collection: MarkingPeriod.simple_periods{|m|[ m.name, m.id ]}, prompt: "Choose marking period" %>
          <%= f.input :transcript_pages, as: :file, label:"Transcript", direct_upload: true, input_html: {multiple: true, accept: "image/png,image/jpeg,application/pdf"}%>

          <%unless @report_card.new_record?%>
            <div class="m-2 p-2 text-sm">
              <b>Existing Transcript</b>
              <ul class="list-group list-group-unbordered mb-3 text-info">
                <li class="list-group-item">
                  <b>Date uploaded</b> <a class="float-right"><%=@report_card.transcript.created_at%></a>
                </li>
              </ul>
            </div>
          <%end%>
        </div>
        <div class="card-footer">
          <%= f.button :submit, "Submit", :class => 'btn btn-primary' %>
          <%= link_to "Cancel", report_cards_path, :class => 'btn btn-default float-right' %>
        </div>
      </div>

    </div>

  </div>

<% end %>

app/views/report_cards/_grade_table.html.erb
<table id="grades_table" class="table" >
  <thead>
    <tr>
      <th>Subject</th><th>Grade</th><th>Remove?</th>
    </tr>
  </thead>
  <tbody>
    <%=f.simple_fields_for :grades,  @report_card.grades do |builder|%>
    <%= render :partial => 'grade_fields', locals: {f: builder} %>
<%end%>
  </tbody>
</table>
<%= link_to_add_fields "Add Grade", f %>

app/views/report_cards/_report_card_table.html.erb
<% if report_cards.count > 0 %>
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>Student</th>
        <th>Session</th>
        <th>Term</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% report_cards.each do |report_card| %>
        <tr>
          <td><%= report_card.student_name %></td>
          <td><%= link_to report_card.marking_period_name, report_card_path(report_card) %></td>
          <td><%=report_card.academic_year%></td>
          <td>

            <%if report_card.transcript.attached?%>
              <%= link_to url_for(report_card.transcript), class: 'btn' do %>
                <i class="fa fa-download"></i>
              <%end%>
            <%end%>

            <%= link_to report_card_path(report_card),
              :method => :delete,
              :data => { :confirm => 'Are you sure?' },
              :class => 'btn' do%>
              <i class="fa fa-trash"></i>
            <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>


<%else%>
  <div class="p-2 pt-2 text-info">No report cards submitted for <%=type%> year</div>
<% end %>

app/views/report_cards/_transcript_iframe.html.erb
<iframe class= 'transcript-viewer' src="<%=report_card.transcript.attached? ? url_for(report_card.transcript): asset_path('upload-transcript.pdf') %>"></iframe>

app/views/report_cards/edit.html.erb
<%=content_for :page_hdr do%>
 Edit Report Card
<%end%>
<%= render :partial => 'form' %>

app/views/report_cards/index.html.erb
<%content_for :page_hdr do%>
  Manage Report Cards
<%end%>
<div class="row">
  <div class="col-sm-12 col-md-10">
    <div class="card card-secondary">
      <div class="card-header d-flex">
        <h3 class="card-title">Uploaded Transcripts By Season: </h3>
        <ul class="nav nav-pills ml-auto">
          <li class="nav-item"><a class="nav-link active show" href="#tab_1" data-toggle="tab">Current</a></li>
          <li class="nav-item"><a class="nav-link " href="#tab_2" data-toggle="tab">Previous</a></li>
        </ul>
      </div>
      <div class="card-body table-responsive p-0">
        <div class="tab-content">
          <div class="tab-pane active show" id="tab_1">
            <%= render "report_card_table", {report_cards: @report_cards.current, type: "current"} %>
          </div>
          <div class="tab-pane " id="tab_2">
            <%= render "report_card_table", {report_cards: @report_cards.previous, type: "previous"} %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-5">
    <%=form_tag new_report_card_path, method: :get do %>

      <div class="card card-light">
        <div class="card-header">

          Select student to upload new report card
        </div>
        <div class="card-body">
          <div class="form-group">
            <%=label_tag "Student List"%>
            <%=select_tag "student_id", options_from_collection_for_select(current_user.students, :id, :name), prompt: "Select student", class: 'form-control'%>
          </div>
        </div>

        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/report_cards/new.html.erb
<%=content_for :page_hdr do%>
 New Report Card
<%end%>
<%= render :partial => 'form' %>

app/views/report_cards/show.html.erb
<%=content_for :page_hdr do%>
  <%=" Report Card #{@report_card.student_name} "%> 
<%end%>
<%=content_for :page_sub_hdr do%>
  <%="#{@report_card.slug}"%> 
<%end%>
<div class="row">
  <!-- left column -->
  <div class="col-md-7">
    <div class="card">
      <div class="card-header bg-info">
        <h3 class="card-title">Transcript Viewer</h3>
      </div>
      <div class="card-body p-0">
        <%= render "transcript_iframe", {report_card: @report_card} %>
      </div>
      <div class="card-footer">
        <%= link_to "Edit Report Card", edit_report_card_path(@report_card), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="col-md-5">
    <div class="card">
      <div class="card-header bg-info">
        <h3 class="card-title">Grades</h3>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped table-valign-middle">
          <thead>
            <tr>
              <th>Subject</th>
              <th>Grade</th>
              <th>Number Grade</th>
            </tr>
          </thead>
          <tbody>
            <%@report_card.grades.each do|grade| %>
              <tr>
                <td><%=grade.subject_name %></td>
                <td>
                  <%=grade.value %>
                </td>
                <td>
                  <%=grade.normalize_to_hundred_point%>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>