config/routes.rb
require 'sidekiq/web'
Pwf::Application.routes.draw do

  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_scope :user do
    get "login", to:  "sessions#new"
    get "logout", to: "sessions#destroy"
    get "users", to: "sessions#new"
  end

  root to: "home#index"


  get 'dashboard', :to => 'dashboards#show'
  get 'registration_closed' => "home#closed", :as => :registration_closed
  get 'registration_confirmation/:registration_id', to: 'student_registration_confirmations#show', as: :registration_confirmation
  get 'edit_my_waitlist', to: 'parent_waitlist#edit', as: :edit_my_waitlist
  patch 'update_my_waitlist', to: 'parent_waitlist#update', as: :update_my_waitlist
  get 'waitlist_upated', to: 'parent_waitlist#thanks', as: :waitlist_updated

  resources :groups
  resources :aep_registrations
  resources :aep_sessions
  resources :attendances
  resources :attendance_sheets do
   resources :attendances
  end

  resources :contact_details

  resources :grades
  resources :monthly_reports
  resources :parents do
    resources :demographics
  end
  resources :payments, only: [:new, :index,:show, :create] do
    collection do
      get :paypal_success
      get :paypal_cancel
      post :notify
    end
  end

  resources :report_cards do
    get :transcript, :on => :member
  end

  resources :seasons

  resources :student_registrations do
    get :withdraw, on: :member
  end

  resources :student_assessments
  resources :students do
    get :avatar, :on => :member
  end

  resources :image_uploads, :only => [:create]

end

app/controllers/parent_waitlist_controller.rb
class ParentWaitlistController < ParentsController
  layout 'plain'

  def update
    @parent.assign_attributes(parent_params)
    if @parent.save
      redirect_to waitlist_updated_path, notice: "Settings updated. You will now be logged out"
    else
      render :edit, layout: nil
    end
  end

  def thanks
    sign_out(current_user)
  end

end

app/views/parent_waitlist/edit.html.erb
<div class="row">
  <div class="col-md-7 col-sm-12 mx-auto">
    <%= placeholder_form_for(@parent, as: :parent, url: update_my_waitlist_path ) do |f| %>
      <%= f.error_notification %>
      <div class="card card-secondary">
        <div class="card-header">
          <h3 class="card-title">Peter Westbrook Foundation Waitlist</h3>
        </div>
        <div class="card-body">
          <div id="accordion">
            <div class="card card-light">
              <div class="card-header">
                <h4 class="card-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="collapsed text-info" aria-expanded="false">
                   Waitlist Notification Settings 
                  </a>
                </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse show" style="">
                <div class="card-body">
                  <div class = "form-row my-2">
                    <div class = "col-sm-12">
                      <h3><%="#{current_user.name} (#{current_user.email})"%></h3>
                    </div>
                    <div class = "col-md-6 col-sm-12">
                      <h3><%=%></h3>
                    </div>
                  </div>
                  <%=f.hidden_field :validate_user_fields_only,  value: true%> 
                  <div class = "form-row">
                    <div class = "col-sm-12">
                      <%= f.input :keep_and_notify_if_waitlisted, label: "Would you like to stay on the waitlist and be notified if spots open up in the future?", as: :radio_buttons, checked_value: "No"%>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div class="card-footer clearfix">
            <%= f.button :submit, "Save", :class => "btn btn-primary btn-large"%>
          </div>
        </div>
      <% end %>
      </div>
  </div>

app/views/parent_waitlist/thanks.html.erb
<div class ="row">
  <div class="col-sm-8 mx-auto my-5">
    <h2 class="text-center my-4"> Thanks for updating your profile and helping us manage the waitlist!</h2>

    <p>
    If you have asked to keep your spot on the waitlist open,  we will notify you if and when space becomes available in the program.
    </p>

    <p>
    Thanks again for your cooperation.
    </p>
  </div>
</div>